[project]
name = "valueselect"
version = "0.1.0"
description = "HTMX Cascading Dropdowns Example"
requires-python = ">=3.8"
dependencies = [
    "flask"
]

[project.optional-dependencies]
dev = [
    "rope"
]
data-retrieval = [
    "beautifulsoup4",
    "requests"
] 