[project]
name = "valueselect"
version = "0.1.0"
description = "HTMX VALUESELECT Example"
requires-python = ">=3.8"
dependencies = [
    "flask",
    "beautifulsoup4",
    "requests"
]

[project.optional-dependencies]
dev = [
    "rope"
] 