[project]
name = "activesearch"
version = "0.20.0"
description = "HTMX Active Search Example"
requires-python = ">=3.8"
dependencies = [
    "flask",
    "flask-restful"
]

[project.optional-dependencies]
dev = [
    "rope",
    "flake8"
]

[tool.setuptools]
packages = []