[project]
name = "ply3"
version = "0.7.2"
description = "HTMX PLY3 Example"
requires-python = ">=3.9"
dependencies = [
    "flask"
]
[project.optional-dependencies]
dev = [
    "flake8"
]
[tool.setuptools]
packages = []